#!/bin/bash

# SPLASH MESSAGE
echo
echo "Installer Script - m1bi - Software Selection (1)."
echo "-----"
echo "- Update Apt-get & Install software from repositories w/ apt-get."
echo "- Install PhoneInfoga w/ Curl."
echo "- Set up Fortunes in ~/.bashrc ."
echo "- Fix & backup /etc/resolv.conf -> /etc/resolv.conf.bak ."
echo
echo "running..."
echo
echo "-- STARTING INSTALLER SCRIPT"
echo "   -----"
# SETUP PREFERRED OR REQUIRED SOFTWARE.
echo
echo "- UPDATING APT SOURCES FROM REPOSITORIES"
echo "  -----"
echo
sudo apt update
echo
echo "-- done."
echo
echo "- PERFORMING UPGRADE ON SYSTEM"
echo "  -----"
echo
sudo apt-get -y upgrade
echo
echo "-- done."
echo
echo "- PERFORMING DISTRIBUTION UPGRADE"
echo
sudo apt-get -y dist-upgrade
echo
echo "-- done."
echo
echo "- SETTING UP YOUR PREFERRED OR REQUIRED YOUR SOFTWARE."
echo "- DOWNLOAD THE FOLLOWING FROM APT-GET REPOSITORIES:"
echo "  -----"
echo 'linux-headers-`uname -r` python3-pip g++ htop neofetch terminator armitage npm etherape libreoffice bpytop fortunes virtualbox vlc sherlock gimp npm irssi'
echo
echo "- INSTALLING AND SETTING UP SOFTWARE FROM APT REPOSITORIES."
echo "  -----"
echo
sudo apt-get -y install linux-headers-`uname -r` python3-pip g++ htop neofetch terminator armitage npm etherape libreoffice bpytop fortunes virtualbox vlc sherlock gimp npm irssi
echo
echo "-- done."
echo
echo "- CLEANING LIBRARIES AND AUTOREMOVE OBSOLETE AND NO LONGER USED PACKAGES."
echo "  -----"
echo
sudo apt -y autoclean && sudo apt -y autoremove
echo
echo "-- done."
echo
# SETUP PHONEINFOGA
echo
echo "- SETTING UP PHONEINFOGA"
echo "  -----"
echo
curl -sSL https://raw.githubusercontent.com/sundowndev/phoneinfoga/master/support/scripts/install | bash
echo
echo "-- done."
echo
# SETUP FORTUNES ON BASH LOGIN
echo
echo "- WRITING FORTUNE TO ~/.BASHRC FOR STARTING FORTUNES ON TERMINAL LAUNCH."
echo "  -----"
echo "echo" >> ~/.bashrc
echo "fortune" >> ~/.bashrc
echo "echo" >> ~/.bashrc
echo "..."
echo
echo "-- done."
echo
# CHANGE /ETC/RESOLV.CONF
echo
echo "- WRITING NEW DNS SERVER TO /ETC/RESOLV.CONF."
echo "  -----"
sudo cp /etc/resolv.conf /etc/resolv.conf.bak
sudo echo "# Generated by NetworkManager" > /tmp/resolv.conf.1
sudo echo "search fritz.box" >> /tmp/resolv.conf.1
sudo echo "nameserver 1.1.1.1" >> /tmp/resolv.conf.1
sudo mv /tmp/resolv.conf.1 /etc/resolv.conf
sudo chown root:root /etc/resolv.conf
echo "..."
echo
echo "-- done."
# EXIT SCRIPT
echo
# EXIT SHELL
echo
echo "-- finished script!"
echo "  (we have the following fortune cookie from me to you.)"
echo "   ----->"
echo
fortune
echo
exit 0
